import type { CollectionConfig } from "./types";

export const watchConfig: CollectionConfig = {
  label: "watch",
  table: "watch_items",
  alias: "wi",
  imagesTable: "watch_images",
  imageFkColumn: "watch_item_id",
  valuationsTable: "watch_valuations",
  valuationFkColumn: "watch_item_id",
  validCategories: ["luxury-watches", "sport-watches", "dress-watches", "vintage-watches"],
  fields: [
    { name: "brand", required: true, trim: true },
    { name: "model", required: true, trim: true },
    { name: "year" },
    { name: "reference_number", trim: true },
    { name: "case_diameter", trim: true },
    { name: "serial_number", trim: true },
    { name: "condition", required: true },
    { name: "purchase_price" },
    { name: "purchase_source", trim: true },
    { name: "dial_color", trim: true },
    { name: "country_of_manufacture", trim: true },
    { name: "movement", trim: true },
    { name: "bracelet_material", trim: true },
    { name: "case_material", trim: true },
    { name: "short_description", trim: true },
    { name: "link", trim: true },
    { name: "notes", trim: true },
  ],
  conditionRequired: true,
  patchSetUpdatedAt: false,
  forceDynamic: false,
};
